# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            make create_env
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Lint
          command: |
            make lint
      - run:
          name: Test
          command: |
            make run_tests
      - store_artifacts:
          path: htmlcov/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/