version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
  neo4j:
    image: "neo4j:3.5.7"
    ports:
      - "7474:7474"
      - "7687:7687"
